#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-unix
Version  : 1.5.7
Release  : 46
URL      : https://cran.r-project.org/src/contrib/unix_1.5.7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/unix_1.5.7.tar.gz
Summary  : POSIX System Utilities
Group    : Development/Tools
License  : MIT
Requires: R-unix-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
POSIX functions which are not part of the Standard C Library.

%package lib
Summary: lib components for the R-unix package.
Group: Libraries

%description lib
lib components for the R-unix package.


%prep
%setup -q -n unix
pushd ..
cp -a unix buildavx2
popd
pushd ..
cp -a unix buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1714076424

%install
export SOURCE_DATE_EPOCH=1714076424
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/unix/DESCRIPTION
/usr/lib64/R/library/unix/INDEX
/usr/lib64/R/library/unix/LICENSE
/usr/lib64/R/library/unix/Meta/Rd.rds
/usr/lib64/R/library/unix/Meta/features.rds
/usr/lib64/R/library/unix/Meta/hsearch.rds
/usr/lib64/R/library/unix/Meta/links.rds
/usr/lib64/R/library/unix/Meta/nsInfo.rds
/usr/lib64/R/library/unix/Meta/package.rds
/usr/lib64/R/library/unix/NAMESPACE
/usr/lib64/R/library/unix/NEWS
/usr/lib64/R/library/unix/R/unix
/usr/lib64/R/library/unix/R/unix.rdb
/usr/lib64/R/library/unix/R/unix.rdx
/usr/lib64/R/library/unix/help/AnIndex
/usr/lib64/R/library/unix/help/aliases.rds
/usr/lib64/R/library/unix/help/paths.rds
/usr/lib64/R/library/unix/help/unix.rdb
/usr/lib64/R/library/unix/help/unix.rdx
/usr/lib64/R/library/unix/html/00Index.html
/usr/lib64/R/library/unix/html/R.css
/usr/lib64/R/library/unix/tests/testthat.R
/usr/lib64/R/library/unix/tests/testthat/test-forking.R
/usr/lib64/R/library/unix/tests/testthat/test-process.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/unix/libs/unix.so
/V4/usr/lib64/R/library/unix/libs/unix.so
/usr/lib64/R/library/unix/libs/unix.so
